project:
  type: website

website:
  title: "Krystal's M10 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "Lee, Krystal-W10 Dashboards Assignment.qmd"
        text: "W10 Dashboards Assignment"
      - href: dashboard.qmd
        text: Dashboard
      - href: shiny-essay.qmd
        text: Shiny Apps Essay
      - href: shinylive.qmd
        text: Shinylive Essay
      
format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    toc-depth: 3
