project:
  type: website

website:
  title: "Krystal's M10 Website"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - href: dashboard.qmd
        text: Dashboard
      - href: shiny-essay.qmd
        text: Shiny Apps Essay
      - href: shinylive.qmd
        text: Shinylive Essay
      
format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    toc-depth: 3
